### ISSUE TITLE
GCC-4.4 issues with Internal Compiler Error 

### ISSUE THREAD

**Issue by gouedard** [dagss/libsharp#1]
Hi ,
You specified  gcc-4xx as good in Readme.compilation. 
I want just to point out that gcc-4.4 gives an internal compiler error.
However, gcc-4.6.3 is ok !

---In function 'calc_map2alm_1_1':
$HOME/local/src/libsharp-code/libsharp/sharp_core_inc2.c:222: erreur interne du compilateur: dans extract_component, à tree-complex.c:616

Cheers!

**Comment by dagss** [comment]
Thanks. Note that this GitHub account is a mirror of the official repo 
at http://sourceforge.net/projects/libsharp/

I've forwarded the message to Martin Reinecke and am closing the issues 
tab for this repo on GitHub.

Dag Sverre
