### ISSUE TITLE
Tag/Release versions

### ISSUE THREAD

**Issue by nilsdeppe** [dagss/libsharp#16]
Hi!

Thanks for the great library. We're looking at using it in our code [SpECTRE](https://github.com/sxs-collaboration/spectre) and were wondering if it would be possible to have versions tagged. This would make libsharp easier to distribute in package managers like [spack](https://github.com/spack/spack).

Cheers,

Nils

**Comment by mreineck** [comment]
Sure, no problem!

**Comment by mreineck** [comment]
Please let me know if this works for you.

**Comment by mreineck** [comment]
Sorry, I updated the version number from 1.0 to 1.0.0 to conform to existing practice.

**Comment by nilsdeppe** [comment]
That'll work perfectly. Thank you for doing this so quickly!

Cheers,

Nils
