### ISSUE TITLE
make fails with mysterious error

### ISSUE THREAD

**Issue by fam14c** [dagss/libsharp#17]
Hello,

While attempting to install libsharp, I first ran the configure script with seemingly no issues:

> student4@astro4:~/libsharp-master> ./configure --prefix=/home/student4/.local
> configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
> checking for uname... 1
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking for gcc option to support OpenMP... -fopenmp
> Using gcc version 8
> configure: creating ./config.status
> config.status: creating config/config.auto

But make then fails with a strange error:

> student4@astro4:~/libsharp-master> make
> using configuration 'auto'
>   compiling libsharp/sharp_testsuite.c
> In file included from /usr/include/features.h:428,
>                  from /usr/local/include/bits/libc-header-start.h:33,
>                  from /usr/include/stdio.h:27,
>                  from /data/astro4_5/student4/libsharp-master/libsharp/sharp_testsuite.c:31:
> /usr/local/include/bits/math-finite.h:57:1: error: conflicting types for ‘acos_MSUF_’
>  __MATH_REDIRCALL (acos, , (_Mdouble_));
>  ^~~~~~~~~~~~~~~~
> compilation terminated due to -Wfatal-errors.
> make: *** [/data/astro4_5/student4/libsharp-master/config/rules.common:19: /data/astro4_5/student4/libsharp-master/build.auto/libsharp/sharp_testsuite.o] Error 1

My gcc compiler and C libraries are up to date, and the web has been no help with this issue. I would really appreciate any assistance.

Felipe Maldonado
Florida State University

**Comment by mreineck** [comment]
This is definitely one of the strangest error messages I've seen so far ... and I've seen quite a lot.

My only guess is that it may be somehow related to:
`configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu`
Can you have a look at this file and see if anythong fishy is going on there?

You can also try rerunning configure with `--enable-noisy-make` and post the output. Maybe configure adds some weird command line flags which lead to this confusion.

**Comment by fam14c** [comment]
Thank you for your reply.

I tried rerunning configure with `--enable-noisy-make` and then make again, there was no difference in the error, so I'll spare you the output.

I took a look at what that `/usr/share/site/x86_64-unknown-linux-gnu` script was. It's a site script for configure scripts, according to its own comments. I'm afraid I have no idea if it's standard or not, so I don't know if it's actually the source of the issue. Here it is,

> student4@astro4:~> more /usr/share/site/x86_64-unknown-linux-gnu
> #!/bin/sh
> \# Site script for configure. It is resourced via $CONFIG_SITE environment varaible.
> 
> \# If user did not specify libdir, guess the correct target:
> \# Use lib64 for 64 bit bi-arch targets, keep the default for the rest.
> if test "$libdir" = '${exec_prefix}/lib' ; then
> 
> 	ac_config_site_64bit_host=NONE
> 
> 	case "$host" in
> 	"" )
> 		# User did not specify host target.
> 		# The native platform x86_64 is a bi-arch platform.
> 		# Try to detect cross-compilation to inferior architecture.
> 
> 		# We are trying to guess 32-bit target compilation. It's not as easy as
> 		# it sounds, as there is possible several intermediate combinations.
> 		ac_config_site_cross_to_32bit_host=NONE
> 
> 		# User defined -m32 in CFLAGS or CXXFLAGS or CC or CXX:
> 		# (It's sufficient for 32-bit, but alone may cause mis-behavior of some checks.)
> 		case "$CFLAGS $CXXFLAGS $CC $CXX" in
> 		*-m32*)
> 			ac_config_site_cross_to_32bit_host=YES
> 			;;
> 		esac
> 
> 		# Running with linux32:
> 		# (Changes detected platform, but not the toolchain target.)
> 		case "`/bin/uname -i`" in
> 		x86_64 | ppc64 | s390x | aarch64 )
> 			;;
> 		* )
> 			ac_config_site_cross_to_32bit_host=YES
> 			;;
> 		esac
> 
> 		if test "x$ac_config_site_cross_to_32bit_host" = xNONE; then
> 			ac_config_site_64bit_host=YES
> 		fi
> 
> 		;;
> 	*x86_64* | *ppc64* | *s390x* | *aarch64* )
> 		ac_config_site_64bit_host=YES
> 		;;
> 	esac
> 
> 	if test "x$ac_config_site_64bit_host" = xYES; then
> 		libdir='${exec_prefix}/lib64'
> 	fi
> fi
> 
> \# If user did not specify libexecdir, set the correct target:
> \# Nor FHS nor openSUSE allow prefix/libexec. Let's default to prefix/lib.
> 
> if test "$libexecdir" = '${exec_prefix}/libexec' ; then
> 	libexecdir='${exec_prefix}/lib'
> fi
> 
> \# Continue with the standard behavior of configure defined in AC_SITE_LOAD:
> if test "x$prefix" != xNONE; then
> 	ac_site_file1=$prefix/share/config.site
> 	ac_site_file2=$prefix/etc/config.site
> else
> 	ac_site_file1=$ac_default_prefix/share/config.site
> 	ac_site_file2=$ac_default_prefix/etc/config.site
> fi
> for ac_site_file in "$ac_site_file1" "$ac_site_file2"
> do
> 	test "x$ac_site_file" = xNONE && continue
> 	if test /dev/null != "$ac_site_file" && test -r "$ac_site_file"; then
> 		{ $as_echo "/usr/share/site/x86_64-unknown-linux-gnu:${as_lineno-$LINENO}: loading site script $ac_site_file" >&5
> $as_echo "/usr/share/site/x86_64-unknown-linux-gnu: loading site script $ac_site_file" >&6;}
> 		sed 's/^/| /' "$ac_site_file" >&5
> 		. "$ac_site_file" \
> 			|| { { $as_echo "/usr/share/site/x86_64-unknown-linux-gnu:${as_lineno-$LINENO}: error: in \`$ac_pwd':" >&5
> $as_echo "/usr/share/site/x86_64-unknown-linux-gnu: error: in \`$ac_pwd':" >&2;}
> as_fn_error $? "failed to load site script $ac_site_file
> See \`config.log' for more details" "$LINENO" 5; }
> 	fi
> done

I forgot to mention that this is a cluster, but since it has up to date compilers and C libraries and autoconf, I didn't think it would be a problem. I installed libsharp on my personal computer without any issues.

Once again, I appreciate your assistance.

**Comment by mreineck** [comment]
> I tried rerunning configure with --enable-noisy-make and then make again, there was no difference in the error, so I'll spare you the output.

During `make`, instead of `compiling libsharp/sharp_testsuite.c` you should have seen the command line used to invoke the compiler. The flags put by `configure` on that line might be helpful.

Otherwise I'm pretty much at my wits' end...

If you only need libsharp's SHT functionality (not the Legendre transform), you might also have a look at my current experimental version (https://gitlab.mpcdf.mpg.de/mtr/libsharp), which has an even more efficient algorithm, but I'm skeptical whether its configure script will work if this one doesn't.

Have you managed to build any other packages with `autoconf` on that machine?

**Comment by fam14c** [comment]
This is the output of `make` with `--enable-noisy-make` on:

> student4@astro4:~/libsharp> make
> using configuration 'auto'
> \#  compiling libsharp/sharp_testsuite.c
> cd /data/astro4_5/student4/libsharp/build.auto/libsharp && gcc  -I/data/astro4_5/student4/libsharp/c_utils -I/data/astro4_5/student4/libsharp/libfftpack -I/data/astro4_5/student4/libsharp/libsharp -I/data/astro4_5/student4/libsharp/build.auto -O3 -fno-tree-vectorize -ffast-math -fomit-frame-pointer -std=c99 -pedantic -Wextra -Wall -Wno-unknown-pragmas -Wshadow -Wmissing-prototypes -Wfatal-errors -march=native  -fopenmp -fPIC   -c /data/astro4_5/student4/libsharp/libsharp/sharp_testsuite.c
> In file included from /usr/include/features.h:428,
>                  from /usr/local/include/bits/libc-header-start.h:33,
>                  from /usr/include/stdio.h:27,
>                  from /data/astro4_5/student4/libsharp/libsharp/sharp_testsuite.c:31:
> /usr/local/include/bits/math-finite.h:57:1: error: conflicting types for ‘acos_MSUF_’
>  __MATH_REDIRCALL (acos, , (_Mdouble_));
>  ^~~~~~~~~~~~~~~~
> compilation terminated due to -Wfatal-errors.
> make: *** [/data/astro4_5/student4/libsharp/config/rules.common:19: /data/astro4_5/student4/libsharp/build.auto/libsharp/sharp_testsuite.o] Error 1

I tried the current experimental version, but unfortunately, it doesn't work for me, because I need to call the libsharp routines from the [pixell](https://github.com/simonsobs/pixell) python package, and the developer just explained to me that the experimental version doesn't produce the things pixell needs to link to it.

I haven't built anything that requires autoconf on this machine yet, but because it is up to date and runs without complaint, I didn't think it was an issue.

**Comment by mreineck** [comment]
OK, I have run several tests here, and I simply don't manage to provoke a similar error locally
I'm pretty sure that something is a bit inconsistent with the setup of the cluster; for example, the compiler finds "stdio.h" in /usr/include/ as expected, but it finds "math-finite.h" somewhere under /usr/local/include instead, which I would have expected to be in /usr/include as well.

To resolve this, you probably have to talk to the admininstrator who configured the cluster. Sorry.

**Comment by mreineck** [comment]
Can you try to compile a C file containing just the single line

#include <stdio.h>

with `gcc -c test.c`?

If that also breaks, it's definitely a problem with the local setup.

**Comment by fam14c** [comment]
I tried compiling the C file as you suggested, and it worked. I also thought to add `#include <math.h>` and it still worked.
I'll talk to the system administrator and see if there's anything to be done from this side.

**Comment by mreineck** [comment]
This is really getting mysterious....

The next thing I would try is to compile this file with the flags from the Makefile, i.e.

`-I/data/astro4_5/student4/libsharp/c_utils -I/data/astro4_5/student4/libsharp/libfftpack -I/data/astro4_5/student4/libsharp/libsharp -I/data/astro4_5/student4/libsharp/build.auto -O3 -fno-tree-vectorize -ffast-math -fomit-frame-pointer -std=c99 -pedantic -Wextra -Wall -Wno-unknown-pragmas -Wshadow -Wmissing-prototypes -Wfatal-errors -march=native -fopenmp -fPIC`

This should break. If it doesn't, I'm completely at my wits' end.
If it does, you can reduce the compiler flags until you find the offending one. Hopefully this will give us further clues...

**Comment by fam14c** [comment]
I did as you suggested, and it did break. I took away the compiler flags one by one, and found that the offending one is `-ffast-math`.

I tried turning off `-Wfatal-errors` to see if anything changes, and the only difference I see is that I get an additional line with the previous definition (but it looks identical) and a long list of other math.h functions that also have this error, so I'll only post the first one to keep it short.

```
student4@astro4:~/test> gcc -ffast-math test.c
In file included from /usr/include/features.h:428,
                 from /usr/local/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from test.c:1:
/usr/local/include/bits/math-finite.h:57:1: error: conflicting types for ‘acos_MSUF_’
 __MATH_REDIRCALL (acos, , (_Mdouble_));
 ^~~~~~~~~~~~~~~~
/usr/local/include/bits/math-finite.h:57:1: note: previous declaration of ‘acos_MSUF_’ was here
 __MATH_REDIRCALL (acos, , (_Mdouble_));
 ^~~~~~~~~~~~~~~~
```


In case we can't fix this.... how affected will libsharp's performance be if I were to turn `-ffast-math` off?

**Comment by mreineck** [comment]
Switching `-ffast-math` off will probably slow down the code by a factor around 1.5.

But please show this small testcase to your administrator! If such a simple compilation test fails, something is definitely incorrectly configured and it will also cause problems for other users. I'm confident that it won't be too hard to fix.

**Comment by fam14c** [comment]
The problem is now solved. Apparently, there was a duplicate of `math-finite.h` (and probably other things) located at `/usr/local/include/bits/`, that were being linked in addition to the headers in the standard place. I don't know why `-ffast-math` was the only affected flag, but changing the name of the directory took it out of the path of the linker, and now the issue is gone.

Thank you for your assistance.

**Comment by mreineck** [comment]
Very good to hear that you were able to locate and solve this!
