### ISSUE TITLE
Equivalent of HEALPix iter

### ISSUE THREAD

**Issue by zonca** [dagss/libsharp#19]
`map2alm` in healpy/HEALPix accepts a `iter` argument, is there anything equivalent in `libsharp`/MPI?

**Comment by mreineck** [comment]
Libsharp doesn't have any equivalent at the moment. As far as I understand, the iterative solver only makes sense for Healpix. Also, the library would have to allocate space for a temporary set of a_lm or a map.

Implementing this on the user side is not hard fortunately. For an exmple, see map2alm_iter in Healpix_cxx/alm_healpix_tools.cc. On the high-level language side, this can be done with about 10 lines. For libsharp it would be much harder.
