### ISSUE TITLE
./configure

### ISSUE THREAD

**Issue by jhparkes** [dagss/libsharp#20]
This may seem like a silly issue, but according to the README file there should be a file called ./configure. However, I cannot locate it. I tried the ./configure.ac file however it fails on the first line do to an unexpected syntax error. I would appreciate any help pointing me to how to properly install libsharp. Thank you.

**Comment by mreineck** [comment]
You are right, in the current state the README is confusing.

The `configure` file is autogenerated from `configure.ac` by the `autoconf` program, which is part of the `autotools`package on most Linux distributions. So you need to install `autotools` first and then run `autoconf`in the package directory. After that, `configure` will be available.

If we had proper release tarballs of libsharp, these would already contain the `configure` file, but we never bothered to provide these.

I'll update the `README`; thanks for reporting this!

**Comment by jhparkes** [comment]
Thank you. That worked perfectly.
